// Kelas Tailwind-like sederhana berbasis objek style inline.
// (Belum pakai Tailwind agar setup ringkas; ganti ke Tailwind kapan saja.)

export const styles = {
  page: {
    maxWidth: 1080,
    margin: '0 auto',
    padding: '24px 16px',
    fontFamily: 'system-ui, -apple-system, Segoe UI, Roboto, sans-serif',
    color: '#1f2937',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '1px solid #e5e7eb',
    paddingBottom: 12,
    marginBottom: 24,
    gap: 16,
    flexWrap: 'wrap',
  },
  nav: { display: 'flex', gap: 12, flexWrap: 'wrap', alignItems: 'center' },
  navLink: {
    textDecoration: 'none',
    color: '#374151',
    fontSize: 14,
    padding: '6px 10px',
    borderRadius: 6,
  },
  button: {
    padding: '8px 14px',
    borderRadius: 8,
    border: '1px solid #d1d5db',
    background: '#fff',
    cursor: 'pointer',
    fontSize: 14,
  },
  buttonPrimary: {
    padding: '8px 14px',
    borderRadius: 8,
    border: '1px solid #2563eb',
    background: '#2563eb',
    color: '#fff',
    cursor: 'pointer',
    fontSize: 14,
  },
  buttonDanger: {
    padding: '6px 10px',
    borderRadius: 6,
    border: '1px solid #dc2626',
    background: '#fff',
    color: '#dc2626',
    cursor: 'pointer',
    fontSize: 13,
  },
  input: {
    padding: '8px 10px',
    borderRadius: 8,
    border: '1px solid #d1d5db',
    fontSize: 14,
    width: '100%',
    boxSizing: 'border-box',
  },
  label: { fontSize: 13, color: '#374151', marginBottom: 4, display: 'block' },
  field: { marginBottom: 14 },
  card: {
    border: '1px solid #e5e7eb',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    background: '#fff',
  },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 14 },
  th: {
    textAlign: 'left',
    borderBottom: '1px solid #e5e7eb',
    padding: '8px 6px',
    color: '#6b7280',
    fontWeight: 600,
  },
  td: { borderBottom: '1px solid #f3f4f6', padding: '8px 6px' },
  error: {
    background: '#fef2f2',
    border: '1px solid #fecaca',
    color: '#991b1b',
    padding: '10px 12px',
    borderRadius: 8,
    fontSize: 14,
    marginBottom: 14,
  },
  badge: {
    display: 'inline-block',
    padding: '2px 8px',
    borderRadius: 999,
    background: '#eff6ff',
    color: '#1d4ed8',
    fontSize: 12,
  },
}
